version: 0.2

phases: 
  install:
    commands:
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt-get install -y nodejs
      - npm install -g serverless
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - serverless deploy --stage dev
  post_build:
    commands:
      - echo Deploy finalizado em `date`
# artifacts:
#   files: 
#     - "**/*"
#   discard-paths: no
#   base-directory: build
